# 配置中心

# 激活环境
spring:
  profiles:
    active: dev

# 日志
logging:
  config: classpath:logback-spring.xml

  # 日志级别
  level:
    com:
      github:
        zhgxun:
          talk:
            dao:
              UserDao: debug

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    interceptors: com.github.zhgxun.talk.common.plugin.GeneralPlugin
server:
  port: 80