# 配置中心

# 激活环境
spring:
  profiles:
    active: dev

# 日志
logging:
  config: classpath:logback-spring.xml

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    interceptors: com.github.zhgxun.talk.common.plugin.GeneralPlugin
server:
  port: 80