# 本地数据源配置
spring:
  datasource:
    name: talk
    url: jdbc:mysql://127.0.0.1:3306/talk?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:

# 日志
logging:
  # 日志级别
  level:
    com:
      github:
        zhgxun:
          talk:
            dao: debug